import CvxLean.Examples.CovarianceEstimation
import CvxLean.Examples.FittingSphere
import CvxLean.Examples.HypersonicShapeDesign
import CvxLean.Examples.OptimalVehicleSpeed
import CvxLean.Examples.TrussDesign
