import CvxLean.Examples.CovarianceEstimation
import CvxLean.Examples.FittingSphere
import CvxLean.Examples.HypersonicShapeDesign
import CvxLean.Examples.TrussDesign
import CvxLean.Examples.VehicleSpeedScheduling
