/*!
Tests from random (non-DCP) problems generated by the DCP quiz:
https://dcp.stanford.edu/quiz
!*/

use egg_convexify::domain;

use egg_convexify::test_util::{*};

#[test]
fn test_quiz_1() {
    convexify_check_expression_with_domain(
        vec![("x", domain::free_dom())], 
        "(inv (inv (var x)))");
}
